# Generated by Django 2.2.3 on 2019-08-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_date_edit0'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date', 'title'], 'permissions': (('view_future_post', 'Can View Unpublished Post'),), 'verbose_name': 'blog post'},
        ),
    ]
