# Generated by Django 2.2.3 on 2019-08-26 12:34

from django.db import migrations
from django.contrib.auth.management import create_permissions




def generate_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    txt = open('crap.txt', 'w')
    txt.write(apps.__str__())
    txt.close()
    try:
        Permission.objects.get(
            codename = "add_post",
            content_type__app_label = "blog")
    except Permission.DoesNotExist:
        models_module = getattr(
            apps, 'models_module', None)
        if models_module is None:
            apps.models_module = True
            create_permissions(apps, verbosity = 0)
            apps.models_module = False
        else:
            raise

def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('blog', '0005_add_view_future_post_permission'),
    ]

    operations = [
        migrations.RunPython(
            generate_permissions,
            reverse_code
        )
    ]
