# Generated by Django 2.2.3 on 2019-07-25 15:25

from django.db import migrations
from datetime import date

NEWSLINKS = [
    {
        "title": "Redundant Homepage Link",
        "link": "http://jambonsw.com",
        "pub_date": date(2013, 1, 18),
        "startup": 'jambon-software',
    },
    {
        "title": "Monkey (Wikipedia)",
        "link": "https://en.wikipedia.org/wiki/Monkey",
        "pub_date": date(2012, 7, 22),
        "startup": "monkey-software",
    },
    {
        "title": "William Shakespeare (Wikipedia)",
        "link": "https://en.wikipedia.org/wiki/William_Shakespeare",
        "pub_date": date(2014, 4, 26),
        "startup": "monkey-software",
    },
]

def add_newslink_data(apps, schema_editor):
    NewsLink = apps.get_model('organiser', 'NewsLink')
    Startup = apps.get_model('organiser', 'Startup')

    for newslink in NEWSLINKS:
        newslink_object = NewsLink.objects.create(
            title = newslink['title'],
            link = newslink['link'],
            pub_date = newslink['pub_date'],
            startup = Startup.objects.get(slug__iexact = newslink['startup'])
        )

def remove_newslink_data(apps, schema_editor):
    NewsLink = apps.get_model('organiser', 'NewsLink')
    Startup = apps.get_model('organiser', 'Startup')
    for newslink in NEWSLINKS:
        newslink_object = NewsLink.objects.get(
            title = newslink['title'],
            link = newslink['link'],
            pub_date = newslink['pub_date'],
            startup = Startup.objects.get(slug__iexact = newslink['startup'])
        )
        newslink_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0005_link_links'),
    ]

    operations = [
        migrations.RunPython(
            add_newslink_data,
            remove_newslink_data
        )
    ]
