# Generated by Django 2.2.3 on 2019-07-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0005_newslink_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newslink',
            unique_together={('slug', 'startup')},
        ),
    ]
