# Generated by Django 2.2.3 on 2019-07-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0006_newslink_unique_together_slug_startup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='tags',
            field=models.ManyToManyField(blank=True, to='organiser.Tag'),
        ),
    ]
