# Generated by Django 2.2.3 on 2019-08-26 12:34

from django.db import migrations
from django.contrib.auth.hashers import make_password


def add_user_data(apps, schema_editor):
    pass

def remove_user_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_permissions'),
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.RunPython(
            add_user_data,
            remove_user_data,
        )
    ]
